# Generated by Django 4.2.10 on 2024-02-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='/media/default.png', upload_to=''),
        ),
    ]
